import { expect, test, type Page, type Request, type APIRequestContext, type APIResponse } from '@playwright/test'

const env = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env || {}
const sandboxURL = env.SEGMENTS_SANDBOX_URL || ''
test.skip(!sandboxURL, 'Requires the isolated real backend; no production fallback.')
// Run with --workers=1; independent reset fixtures allow later tests to report
// their own failures instead of being skipped after an unrelated case fails.
const diagnostics = new Map<Page, string[]>()

async function json(response: APIResponse) {
  expect(response.ok(), `${response.status()} ${response.url()}: ${await response.text()}`).toBeTruthy()
  return response.json()
}

test.beforeEach(async ({ page, request }) => {
  expect(new URL(sandboxURL).hostname).toMatch(/^(127\.0\.0\.1|localhost)$/)
  const state = await json(await request.post(`${sandboxURL}/__sandbox/reset`))
  expect(state.sandbox).toBe(true)
  expect(state.schema).toMatch(/^segments_browser_test_/)
  await page.addInitScript(state => {
    localStorage.setItem('soulcuts-backoffice-theme', 'light')
    localStorage.setItem('backoffice-auth', JSON.stringify({ accessToken: state.access_token, refreshToken: 'sandbox-unused', user: state.user }))
  }, state)
  const issues: string[] = []
  const bodylessDeletes = new Set<Request>()
  diagnostics.set(page, issues)
  page.on('pageerror', error => issues.push(`Uncaught browser exception: ${error.message}`))
  page.on('console', message => { if (message.type() === 'error') issues.push(`Browser console: ${message.text()}`) })
  page.on('response', response => {
    if (response.status() === 204 && response.request().method() === 'DELETE') bodylessDeletes.add(response.request())
    if (response.url().startsWith(`${sandboxURL}/api/`) && response.status() >= 400) {
      issues.push(`Unexpected API response: ${response.status()} ${response.request().method()} ${response.url()}`)
    }
  })
  page.on('requestfailed', request => {
    // Chromium can report ERR_ABORTED while discarding an already successful
    // 204 DELETE body. Require the observed response; real aborted calls fail.
    if (bodylessDeletes.has(request) && request.failure()?.errorText === 'net::ERR_ABORTED') return
    if (request.url().startsWith(`${sandboxURL}/api/`)) issues.push(`Failed API request: ${request.url()} ${request.failure()?.errorText}`)
  })
})

test.afterEach(async ({ page }) => {
  expect(diagnostics.get(page) || [], 'Connected workflows must not hide failed API calls or browser exceptions').toEqual([])
  diagnostics.delete(page)
})

async function backend(request: APIRequestContext) {
  const state = await json(await request.get(`${sandboxURL}/__sandbox`))
  return { state, headers: { Authorization: `Bearer ${state.access_token}` }, root: `${sandboxURL}/api/v1/backoffice` }
}

const starterRules = {
  combine: 'all', conditions: [{ type: 'last_visit_age', min: 3, max: 12, unit: 'calendar_months' }],
  exclusions: [{ type: 'upcoming_booking', present: true }],
}

async function segment(request: APIRequestContext, name: string) {
  const { root, headers } = await backend(request)
  return json(await request.post(`${root}/segments`, { headers, data: { name, rules: starterRules } }))
}

test('customer history and marketing consent affect real campaign contactability', async ({ page, request }) => {
  const { state, root, headers } = await backend(request)
  const savedSegment = await segment(request, 'Consent audience')
  const campaign = await json(await request.post(`${root}/messaging/campaigns`, { headers, data: {
    name: 'Consent campaign', type: 'manual', channel: 'telegram', channel_strategy: 'telegram_then_sms',
    segment_ids: [savedSegment.id], metadata_json: { message_body: 'Sandbox {{client_name}}' },
  } }))
  const preview = async () => json(await request.post(`${root}/messaging/campaigns/${campaign.id}/audience-preview`, { headers }))
  expect((await preview()).items.filter((item: { eligible: boolean }) => item.eligible)).toHaveLength(2)
  await page.goto(`/customers/${state.seed.customers.completed}`)
  await expect(page.getByRole('heading', { name: 'Sandbox completed', exact: true })).toBeVisible()
  await expect(page.getByRole('table', { name: 'Історія послуг клієнта', exact: true })).toContainText('Sandbox haircut')
  await page.getByRole('button', { name: 'Оновити налаштування', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Є маркетингова згода', exact: true }).uncheck()
  const updatedResponse = page.waitForResponse(response => response.url().endsWith(`/customers/${state.seed.customers.completed}/preferences`) && response.request().method() === 'PATCH')
  await page.getByRole('dialog').getByRole('button', { name: 'Зберегти', exact: true }).click()
  expect((await updatedResponse).ok()).toBeTruthy()
  const changed = await preview()
  expect(changed.total).toBe(3)
  expect(changed.items.find((item: { customer_id: number }) => item.customer_id === state.seed.customers.completed).eligible).toBe(false)
  expect(changed.items.filter((item: { eligible: boolean }) => item.eligible)).toHaveLength(1)
  await page.goto(`/messaging/campaigns/${campaign.id}`)
  await page.getByRole('button', { name: 'Перевірити отримувачів', exact: true }).click()
  const audienceRow = page.getByRole('table', { name: 'Попередній перегляд отримувачів', exact: true }).getByRole('row').filter({ hasText: 'Sandbox completed' })
  await expect(audienceRow).toContainText(/Відмова|відмов|згод/)
  await expect(audienceRow.getByRole('link', { name: 'Sandbox completed', exact: true })).toHaveAttribute('href', `/customers/${state.seed.customers.completed}`)
  expect((await json(await request.get(`${root}/messaging/campaigns/${campaign.id}/runs`, { headers }))).total).toBe(0)
  expect((await json(await request.get(`${sandboxURL}/__sandbox`))).recorded_messages).toHaveLength(0)
})

test('inline wizard service catalog uses booking-service IDs and preserves selections when switching audience modes', async ({ page, request }) => {
  const { state, root, headers } = await backend(request)
  const savedSegment = await segment(request, 'Switchable saved audience')
  const catalogs: string[] = []
  page.on('request', request => { if (/\/backoffice\/barbers\/\d+\/services/.test(request.url())) catalogs.push(request.url()) })
  await page.goto('/messaging/campaigns/new')
  await page.getByRole('textbox', { name: 'Назва кампанії', exact: true }).fill('Service audience switching')
  expect(catalogs).toHaveLength(0)
  await page.getByRole('button', { name: 'Далі', exact: true }).click()
  await page.getByText('Використали послугу', { exact: true }).click()
  await expect(page.getByRole('radio', { name: /^Використали послугу/ })).toBeChecked()
  await expect.poll(() => catalogs.length).toBe(1)
  const serviceChoice = page.getByRole('combobox', { name: 'Послуга', exact: true })
  await expect(serviceChoice.getByRole('option', { name: /Sandbox haircut/ })).toHaveAttribute('value', String(state.seed.service_id))
  const estimateResponse = page.waitForResponse(response => response.url().includes('/messaging/audience/estimate')
    && response.request().postDataJSON()?.rules?.some((rule: { service_id?: number }) => rule.service_id === state.seed.service_id))
  await serviceChoice.selectOption(String(state.seed.service_id))
  const estimate = await (await estimateResponse).json()
  expect(estimate.total).toBeGreaterThan(0)
  await page.getByRole('radio', { name: 'Збережені сегменти', exact: true }).check()
  await expect(page.getByRole('radio', { name: 'Збережені сегменти', exact: true })).toBeChecked()
  await expect(page.getByRole('radio', { name: 'Фільтри цієї кампанії', exact: true })).not.toBeChecked()
  await page.getByRole('checkbox', { name: /^Switchable saved audience/ }).check()
  await page.getByRole('radio', { name: 'Фільтри цієї кампанії', exact: true }).check()
  await expect(page.getByRole('radio', { name: 'Фільтри цієї кампанії', exact: true })).toBeChecked()
  await expect(page.getByRole('radio', { name: 'Збережені сегменти', exact: true })).not.toBeChecked()
  await expect(serviceChoice).toHaveValue(String(state.seed.service_id))
  await page.getByRole('radio', { name: 'Збережені сегменти', exact: true }).check()
  await expect(page.getByRole('radio', { name: 'Збережені сегменти', exact: true })).toBeChecked()
  await expect(page.getByRole('radio', { name: 'Фільтри цієї кампанії', exact: true })).not.toBeChecked()
  await expect(page.getByRole('checkbox', { name: /^Switchable saved audience/ })).toBeChecked()
  await page.getByRole('button', { name: 'Далі', exact: true }).click()
  await page.getByRole('textbox', { name: /^Текст/ }).fill('Sandbox mode-switch draft')
  await page.getByRole('button', { name: /^(?:Крок )?6(?::|\s|$)/ }).click()
  const createdResponse = page.waitForResponse(response => response.url().endsWith('/messaging/campaigns') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Зберегти чернетку', exact: true }).click()
  const created = await (await createdResponse).json()
  expect(created.segment_ids).toEqual([savedSegment.id])
  expect(created.metadata_json.audience_rules[0].service_id).toBe(state.seed.service_id)
  expect(created.status).toBe('draft')
  expect((await json(await request.get(`${root}/messaging/campaigns/${created.id}/runs`, { headers }))).total).toBe(0)
})

test('template create/edit and campaign text edits preserve the shared template', async ({ page, request }) => {
  const { root, headers } = await backend(request)
  await page.goto('/messaging/templates')
  await page.getByRole('button', { name: 'Новий шаблон', exact: true }).click()
  const modal = page.getByRole('dialog')
  await modal.getByRole('textbox', { name: 'Назва шаблону', exact: true }).fill('Connected reusable template')
  await modal.getByRole('textbox', { name: /^Текст повідомлення/ }).fill('Original {{client_name}}')
  const createdResponse = page.waitForResponse(response => response.url().includes('/messaging/templates') && response.request().method() === 'POST')
  await modal.getByRole('button', { name: 'Зберегти', exact: true }).click()
  const created = await (await createdResponse).json()
  const row = page.getByRole('row').filter({ hasText: 'Connected reusable template' })
  await row.getByRole('button', { name: 'Редагувати шаблон', exact: true }).click()
  await modal.getByRole('textbox', { name: /^Текст повідомлення/ }).fill('Updated shared {{client_name}}')
  await modal.getByRole('button', { name: 'Зберегти', exact: true }).click()
  await expect(modal).toHaveCount(0)
  const savedSegment = await segment(request, 'Template audience')
  await page.goto(`/messaging/campaigns/new?segment_id=${savedSegment.id}`)
  await page.getByRole('textbox', { name: 'Назва кампанії', exact: true }).fill('Template-backed draft')
  await page.getByRole('button', { name: 'Далі', exact: true }).click()
  await page.getByRole('button', { name: 'Далі', exact: true }).click()
  await page.getByRole('combobox', { name: 'Шаблон', exact: true }).selectOption(String(created.id))
  await expect(page.getByRole('textbox', { name: /^Текст/ })).toHaveValue('Updated shared {{client_name}}')
  await page.getByRole('button', { name: /^(?:Крок )?6(?::|\s|$)/ }).click()
  const campaignResponse = page.waitForResponse(response => response.url().endsWith('/messaging/campaigns') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Зберегти чернетку', exact: true }).click()
  const campaign = await (await campaignResponse).json()
  await expect(page).toHaveURL(new RegExp(`/messaging/campaigns/${campaign.id}$`))
  await page.getByRole('textbox', { name: 'Повідомлення', exact: true }).fill('Only this campaign changed')
  const saveResponse = page.waitForResponse(response => response.url().endsWith(`/campaigns/${campaign.id}`) && response.request().method() === 'PUT')
  await page.getByRole('button', { name: 'Зберегти зміни', exact: true }).click()
  expect((await saveResponse).ok()).toBeTruthy()
  const templates = await json(await request.get(`${root}/messaging/templates?page=1&page_size=100`, { headers }))
  expect(templates.items.find((item: { id: number }) => item.id === created.id).body).toBe('Updated shared {{client_name}}')
  const updated = await json(await request.get(`${root}/messaging/campaigns/${campaign.id}`, { headers }))
  expect(updated.metadata_json.message_body).toBe('Only this campaign changed')
  expect(updated.segment_ids).toEqual([savedSegment.id])
  expect(updated.status).toBe('draft')
  await page.goto('/messaging/templates')
  const originalRow = page.getByRole('row').filter({ has: page.getByText('Connected reusable template', { exact: true }) })
  const duplicateResponse = page.waitForResponse(response => response.url().endsWith(`/templates/${created.id}/duplicate`) && response.request().method() === 'POST')
  await originalRow.getByRole('button', { name: 'Дублювати шаблон', exact: true }).click()
  const duplicate = await (await duplicateResponse).json()
  const duplicateRow = page.getByRole('row').filter({ has: page.getByText(duplicate.name, { exact: true }) })
  await duplicateRow.getByRole('button', { name: 'Видалити шаблон', exact: true }).click()
  const deletion = page.waitForResponse(response => response.url().endsWith(`/templates/${duplicate.id}`) && response.request().method() === 'DELETE')
  const refreshedTemplates = page.waitForResponse(response => response.url().includes('/messaging/templates?') && response.request().method() === 'GET')
  await page.getByRole('dialog').getByRole('button', { name: 'Видалити', exact: true }).click()
  expect((await deletion).ok()).toBeTruthy()
  expect((await refreshedTemplates).ok()).toBeTruthy()
  await expect(page.getByText(duplicate.name, { exact: true })).toHaveCount(0)
  await expect(originalRow).toBeVisible()
})

test('service notification configuration stays event-driven when paused and resumed', async ({ page, request }) => {
  const { state, root, headers } = await backend(request)
  await page.goto('/messaging/notifications')
  await page.getByRole('row').filter({ hasText: 'Sandbox booking notification' }).getByRole('link', { name: 'Деталі', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Sandbox booking notification', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Аудиторія та запуск', exact: true })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Підготовка кампанії', exact: true })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Журнал відправок', exact: true })).toBeVisible()
  const pauseResponse = page.waitForResponse(response => response.url().endsWith(`/campaigns/${state.seed.notification_id}/status`) && response.request().method() === 'PATCH')
  await page.getByRole('button', { name: 'Пауза', exact: true }).click()
  expect((await pauseResponse).ok()).toBeTruthy()
  await expect(page.getByRole('button', { name: 'Поновити', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Поновити', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Пауза', exact: true })).toBeVisible()
  const notification = await json(await request.get(`${root}/messaging/campaigns/${state.seed.notification_id}`, { headers }))
  expect(notification.type).toBe('booking_confirmation')
  expect(notification.purpose).toBe('transactional')
  expect(notification.status).toBe('active')
  expect(notification.segment_ids).toEqual([])
  expect(notification.metadata_json.message_body).toBe('Sandbox booking {{client_name}}')
  expect((await json(await request.get(`${sandboxURL}/__sandbox`))).recorded_messages).toHaveLength(0)
})

test('existing campaign selects overlapping segments, retains offer/schedule, launches sandbox and links delivery history', async ({ page, request }, testInfo) => {
  test.setTimeout(60_000)
  const { state, root, headers } = await backend(request)
  const one = await segment(request, 'Connected return audience')
  const two = await segment(request, 'Overlapping return audience')
  const scheduled = new Date(Date.now() + 86_400_000).toISOString()
  const campaign = await json(await request.post(`${root}/messaging/campaigns`, { headers, data: {
    name: 'Connected scheduled offer', type: 'manual', channel: 'telegram', audience: { all_clients: true },
    scheduled_at: scheduled, discount_code: state.seed.promotion_code, template_id: state.seed.template_id,
  } }))
  await page.goto(`/messaging/campaigns/${campaign.id}`)
  await page.getByRole('checkbox', { name: 'Використовувати збережені сегменти', exact: true }).check()
  await page.getByRole('checkbox', { name: /^Connected return audience/ }).check()
  await page.getByRole('checkbox', { name: /^Overlapping return audience/ }).check()
  await page.getByRole('combobox', { name: 'Стратегія каналів', exact: true }).selectOption('telegram_then_sms')
  const save = async () => {
    const response = page.waitForResponse(response => response.url().endsWith(`/campaigns/${campaign.id}`) && response.request().method() === 'PUT')
    await page.getByRole('button', { name: 'Зберегти зміни', exact: true }).click()
    expect((await response).ok()).toBeTruthy()
    await expect(page.getByRole('button', { name: 'Зберегти зміни', exact: true })).toBeDisabled()
  }
  await save()
  const saved = await json(await request.get(`${root}/messaging/campaigns/${campaign.id}`, { headers }))
  expect([...saved.segment_ids].sort()).toEqual([one.id, two.id].sort())
  expect(new Date(saved.scheduled_at).getTime()).toBe(new Date(scheduled).getTime())
  expect(saved.discount_code).toBe(state.seed.promotion_code)
  await page.getByRole('button', { name: 'Прибрати розклад', exact: true }).click()
  await save()
  await page.getByRole('button', { name: 'Перевірити отримувачів', exact: true }).click()
  await expect(page.getByText('2 / 3', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Перевірити та запустити', exact: true }).click()
  const confirm = page.getByRole('dialog')
  await expect(confirm).toContainText(state.seed.promotion_code)
  await expect(confirm).toContainText('Telegram, інакше SMS')
  expect((await json(await request.get(`${root}/messaging/campaigns/${campaign.id}/runs`, { headers }))).total).toBe(0)
  expect((await json(await request.get(`${sandboxURL}/__sandbox`))).recorded_messages).toHaveLength(0)
  const launchResponse = page.waitForResponse(response => response.url().endsWith(`/campaigns/${campaign.id}/runs`) && response.request().method() === 'POST')
  await confirm.getByRole('button', { name: 'Підтвердити запуск', exact: true }).click()
  const run = await (await launchResponse).json()
  expect(run.audience_count).toBe(3)
  const processed = await json(await request.post(`${sandboxURL}/__sandbox/process`))
  expect(processed.recorded_messages).toHaveLength(2)
  expect(processed.recorded_messages.every((message: { body: string }) => message.body.includes(state.seed.promotion_code))).toBe(true)
  await page.getByRole('button', { name: `Переглянути запуск ${run.id}`, exact: true }).click()
  const results = page.locator('article').filter({ has: page.getByRole('heading', { name: `Запуск #${run.id} · незмінний знімок`, exact: true }) })
  await expect(results.getByText('Надіслано (прийнято провайдером)', { exact: true }).first().locator('..')).toContainText('2')
  await expect(results.getByText('Пропущено', { exact: true }).first().locator('..')).toContainText('1')
  await json(await request.post(`${root}/segments/${one.id}/archive`, { headers }))
  const frozen = await json(await request.get(`${root}/messaging/campaigns/${campaign.id}/runs/${run.id}`, { headers }))
  expect(frozen.segment_snapshots.find((item: { id: number }) => item.id === one.id).revision).toBe(1)
  expect(frozen.campaign_snapshot.discount_code).toBe(state.seed.promotion_code)
  await page.reload()
  const journal = page.locator('#delivery-journal')
  await expect(journal.getByRole('table').getByRole('row')).toHaveCount(4)
  await journal.getByRole('button', { name: /^Канал у журналі/ }).click()
  await page.getByRole('listbox').getByRole('option', { name: 'SMS', exact: true }).click()
  await expect(journal.getByRole('table').getByRole('row')).toHaveCount(2)
  await journal.getByRole('button', { name: /^Статус у журналі/ }).click()
  await page.getByRole('listbox').getByRole('option', { name: 'Прийнято провайдером', exact: true }).click()
  await journal.getByRole('textbox', { name: 'Клієнт у журналі', exact: true }).fill(String(state.seed.customers.imported))
  await expect(journal.getByRole('table').getByRole('row')).toHaveCount(2)
  await expect(journal.getByRole('link', { name: `Повідомлення №${campaign.id}`, exact: true })).toHaveAttribute('href', `/messaging/campaigns/${campaign.id}#delivery-journal`)
  await page.screenshot({ path: testInfo.outputPath('connected-delivery-journal.png'), fullPage: true, animations: 'disabled' })
  await journal.getByRole('link').filter({ hasText: /Клієнт|Sandbox imported/ }).first().click()
  await expect(page).toHaveURL(new RegExp(`/customers/${state.seed.customers.imported}$`))
  await expect(page.getByRole('heading', { name: 'Sandbox imported', exact: true })).toBeVisible()
  await page.goto('/promotions')
  await expect(page.getByText(state.seed.promotion_code, { exact: true })).toBeVisible()
  const offer = await json(await request.get(`${root}/promotions/${state.seed.promotion_id}`, { headers }))
  expect(offer.discount_percent).toBe(10)
  expect(offer.code).toBe(state.seed.promotion_code)
})
