services:
  barbershop:
    build:
      context: .
      dockerfile: ./apps/barbershop/Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3000"

  shop:
    build:
      context: .
      dockerfile: ./apps/shop/Dockerfile
    env_file:
      - .env
    ports:
      - "3002:3000"

  backoffice:
    build:
      context: .
      dockerfile: ./apps/backoffice/Dockerfile
    env_file:
      - .env
    ports:
      - "3003:3000"
