import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const procurement = await readFile(new URL('../pages/inventory/procurement.vue', import.meta.url), 'utf8')
const receiving = await readFile(new URL('../pages/inventory/receiving.vue', import.meta.url), 'utf8')
const counts = await readFile(new URL('../pages/inventory/counts.vue', import.meta.url), 'utf8')

test('procurement groups queue products, exposes requirements, and only marks selected order items', () => {
  assert.match(procurement, /getProcurementQueue/)
  assert.match(procurement, /total_quantity_required/)
  assert.match(procurement, /requirements/)
  assert.match(procurement, /order_id/)
  assert.match(procurement, /order_item_id/)
  assert.match(procurement, /markProcurementOrdered\(\[\.\.\.selectedIds\.value\]\)/)
  assert.match(procurement, /quantity_required/)
  assert.match(procurement, /ordered: item\.quantity/)
  assert.match(procurement, /fromStock: item\.quantity_from_stock/)
  assert.match(procurement, /quantity_received/)
  assert.match(procurement, /procurement_status/)
  assert.match(procurement, /\/inventory\/receiving/)
})

test('receipt workflow has barcode lookup, additive item semantics, allocations, and idempotent create/post protection', () => {
  assert.match(receiving, /<InventoryBarcodeInput v-model="barcode"/)
  assert.match(receiving, /lookupInventoryProductByBarcode/)
  assert.match(receiving, /addInventoryReceiptItem/)
  assert.match(receiving, /quantity: itemQuantity/)
  assert.match(receiving, /Повторне додавання такого самого товару збільшить рядок/)
  assert.match(receiving, /order_item_id/)
  assert.match(receiving, /allocationTotal\.value > itemQuantity/)
  assert.match(receiving, /createInventoryIdempotencyKey\(\)/)
  assert.match(receiving, /postInventoryReceipt/)
  assert.match(receiving, /ConfirmActionModal/)
  assert.match(receiving, /getInventoryReceipt/)
  assert.match(receiving, /watch\(receiptIdFromRoute/)
  assert.match(receiving, /receiptLoadRequest/)
  assert.match(receiving, /receiptIdFromRoute\.value === id/)
  assert.match(receiving, /receiptIdFromRoute\.value !== activeReceipt\.id/)
  assert.match(receiving, /productLookupRequest/)
  assert.match(receiving, /productSearchRequest/)
  assert.match(receiving, /if \(adding\.value \|\| posting\.value \|\| loadingReceipt\.value \|\| pendingStorageError\.value\) return/)
  assert.match(receiving, /cost < 0 \|\| isPosted\.value/)
  assert.match(receiving, /posting\.value \|\| adding\.value/)
  assert.match(receiving, /postKey\.value = ''/)
  assert.doesNotMatch(receiving, /barcode\.value = product\.barcode/)
  assert.match(receiving, /isPosted/)
})

test('count workflow upserts scanned quantities, renders server differences, and prevents draft changes after posting', () => {
  assert.match(counts, /<InventoryBarcodeInput v-model="barcode"/)
  assert.match(counts, /setInventoryCountItem/)
  assert.match(counts, /counted_quantity: itemQuantity/)
  assert.match(counts, /Повторне сканування оновлює це значення, а не додає його/)
  assert.match(counts, /expected_quantity/)
  assert.match(counts, /difference/)
  assert.match(counts, /createInventoryIdempotencyKey\(\)/)
  assert.match(counts, /postInventoryCount/)
  assert.match(counts, /ConfirmActionModal/)
  assert.match(counts, /getInventoryCount/)
  assert.match(counts, /watch\(countIdFromRoute/)
  assert.match(counts, /countLoadRequest/)
  assert.match(counts, /countIdFromRoute\.value === id/)
  assert.match(counts, /countIdFromRoute\.value !== activeCount\.id/)
  assert.match(counts, /productLookupRequest/)
  assert.match(counts, /productSearchRequest/)
  assert.match(counts, /posting\.value \|\| isPosted\.value/)
  assert.match(counts, /posting\.value \|\| savingItem\.value/)
  assert.match(counts, /postKey\.value = ''/)
  assert.doesNotMatch(counts, /barcode\.value = product\.barcode/)
  assert.match(counts, /isPosted/)
})

test('all inventory workflows enforce an admin-only route guard and surface actionable error UI', () => {
  for (const source of [procurement, receiving, counts]) {
    assert.match(source, /auth\.user\?\.is_superuser/)
    assert.match(source, /auth\.user\?\.role !== 'admin'/)
    assert.match(source, /role="alert"/)
  }
})
