import assert from 'node:assert/strict'
import { access, readFile, readdir } from 'node:fs/promises'
import { extname, join, relative } from 'node:path'
import test from 'node:test'

const appRoot = new URL('..', import.meta.url)
const productPage = new URL('../pages/products/[id].vue', import.meta.url)
const ordersListPage = new URL('../pages/orders/index.vue', import.meta.url)
const obsoleteOrdersPage = new URL('../pages/orders.vue', import.meta.url)
const messagingRoots = [
  new URL('../components/messaging', import.meta.url),
  new URL('../pages/messaging', import.meta.url),
]
const customerDetailsPage = new URL('../pages/customers/[id].vue', import.meta.url)
const trashIconComponent = new URL('../components/TrashIcon.vue', import.meta.url)
const baseButtonComponent = new URL('../components/BaseButton.vue', import.meta.url)

const vueFiles = async (directory) => {
  const entries = await readdir(directory, { withFileTypes: true })
  const nested = await Promise.all(entries.map(async (entry) => {
    const path = join(directory, entry.name)
    if (entry.isDirectory()) return vueFiles(path)
    return extname(entry.name) === '.vue' ? [path] : []
  }))
  return nested.flat()
}

test('the product dynamic route handles creation without loading a product named new', async () => {
  const source = await readFile(productPage, 'utf8')

  assert.match(source, /productId\.value === 'new'/)
  assert.match(source, /isNewProduct\.value \? null : await api\.getProduct/)
  assert.match(source, /api\.createProduct\(payload\)/)
  assert.match(source, /router\.replace\(`\/products\/\$\{createdProduct\.id\}`\)/)
  assert.match(source, /submit-label="Створити товар"/)
})

test('orders list and details are sibling routes', async () => {
  await access(ordersListPage)
  await assert.rejects(access(obsoleteOrdersPage))

  const source = await readFile(ordersListPage, 'utf8')
  assert.match(source, /`\/orders\/\$\{order\.id\}`/)
})

test('messaging feature uses the component names generated by Nuxt auto-imports', async () => {
  const paths = [
    ...await Promise.all(messagingRoots.map(root => vueFiles(root.pathname))).then(groups => groups.flat()),
    customerDetailsPage.pathname,
  ]
  const unprefixedComponent = /<(AudienceFilterBuilder|CampaignAnalyticsCards|CampaignRecipientsTable|CampaignStatusBadge|CampaignTypeBadge|ClientCommunicationPanel|MessagePreview|MessageTemplateEditor|RecipientPreviewTable|SendLogsTable|SmsCampaignsPanel|VariablePicker)(?:\s|>)/
  const violations = []

  for (const path of paths) {
    const source = await readFile(path, 'utf8')
    if (unprefixedComponent.test(source)) violations.push(relative(appRoot.pathname, path))
  }

  assert.deepEqual(violations, [])
})

test('customer service history shows visit prices and resolved master names in a paginated table', async () => {
  const source = await readFile(customerDetailsPage, 'utf8')

  assert.match(source, /caption="Історія послуг клієнта"/)
  assert.match(source, /<th>Візит<\/th>/)
  assert.match(source, /<th>Ціна послуг<\/th>/)
  assert.match(source, /<th>Майстер<\/th>/)
  assert.match(source, /booking\.service_prices/)
  assert.match(source, /bookingMasterLabel\(booking\)/)
  assert.match(source, /api\.adminGetMasters\(1, 100\)/)
  assert.match(source, /api\.getCustomerBookings\(customerId\.value, bookingPage\.value, bookingPageSize\)/)
  assert.match(source, /@click="nextBookingPage"/)
})

test('delete buttons use the app-local solid trash icon', async () => {
  const source = await readFile(trashIconComponent, 'utf8')
  const baseButtonSource = await readFile(baseButtonComponent, 'utf8')
  const paths = await vueFiles(appRoot.pathname)
  const externalTrashIconImports = []
  const compactDeleteButtonViolations = []

  assert.match(source, /fill="currentColor"/)
  assert.match(source, /width="1em"/)
  assert.match(source, /height="1em"/)
  assert.match(source, /class="shrink-0"/)
  assert.match(baseButtonSource, /\| 'danger-icon'/)
  assert.match(baseButtonSource, /props\.variant === 'icon' \|\| props\.variant === 'danger-icon'/)
  assert.match(baseButtonSource, /props\.variant === 'danger-icon'\) return 'base-button--danger-outline'/)

  for (const path of paths) {
    if (path === trashIconComponent.pathname) continue
    const fileSource = await readFile(path, 'utf8')
    if (/import[^\n]*TrashIcon[^\n]*@heroicons\/vue/.test(fileSource)) {
      externalTrashIconImports.push(relative(appRoot.pathname, path))
    }
    if (/<BaseButton\b(?=[^>]*\bvariant="danger-outline")[^>]*>(?:(?!<\/BaseButton>)[\s\S])*?<TrashIcon\b/.test(fileSource)) {
      compactDeleteButtonViolations.push(relative(appRoot.pathname, path))
    }
  }

  assert.deepEqual(externalTrashIconImports, [])
  assert.deepEqual(compactDeleteButtonViolations, [])
})
